# Generated by Django 2.2.12 on 2021-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('youtube_id', models.TextField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(db_index=True)),
                ('description', models.TextField(db_index=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('thumbnail_urls', models.ManyToManyField(blank=True, null=True, to='content.VideoThumbnail')),
            ],
        ),
    ]
