# Generated by Django 2.2.12 on 2021-02-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='video',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='video',
            name='published_after',
            field=models.DateTimeField(db_index=True, default=None),
        ),
    ]
